name: Maven/cs32-test CI

# triggers on push or pull request
# or can be run manually from Actions tab
on: [push, pull_request, workflow_dispatch]

jobs:
    linux-package:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup Java 11
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'adopt'
            - name:  Clean Maven
              # clean repository 
              run: mvn clean
            - name: Package Maven
              # package maven
              run: mvn --batch-mode --update-snapshots package
            - name: debug path
              run: pwd && ls
            - name: see where . is
              run: cd . && pwd
            - name: make cs32-test executable
              run: chmod +x ./cs32-test
            - name: make ./run executable
              run: chmod +x ./run
            - name: try running ./run
              run: ./run
            - name: run cs32-test
              # run cs32-test with no web
              run: ./cs32-test -nw
