name: Maven/cs32-test CI

# triggers on push or pull request
# or can be run manually from Actions tab
on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@v3
            - name: Setup Python 3
              uses: actions/setup-python@v3
              with:
                  python-version: '3.9'
            - name: Setup Java 11
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'adopt'
            - name: Maven Clean
              # clean repository 
              run: mvn --batch-mode clean
            - name: Package Maven
              # package maven
              run: mvn --batch-mode --update-snapshots package
            - name: Make cs32-test executable
              run: chmod +x ./cs32-test
            - name: Make ./run executable
              run: chmod +x ./run
            - name: Run cs32-test
              # run cs32-test with no web
              run: ./cs32-test -nw -rt
    coverage:
        needs: build
        runs-on: ubuntu-latest
        steps:
           - uses: actions/checkout@v3
           - name: use codecov bot
             uses: codecov/codecov-action@v2
             with:
                 file: ./.tester-internal/jacoco-report.xml
                 name: jacoco-codecov
                 fail_ci_if_error: true
